# Generated by Django 5.2.1 on 2025-11-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(db_index=True, max_length=32)),
                ('body', models.TextField()),
                ('result', models.CharField(max_length=40)),
                ('provider', models.CharField(default='JBDSMS', max_length=50)),
                ('context', models.CharField(choices=[('CREATED', 'Booking Created'), ('STATUS', 'Status Changed'), ('PAYMENT', 'Payment/Checkout'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('booking_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
