# Generated by Django 5.2.1 on 2025-10-26 04:43

import apps.guests.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('nid_passport', models.CharField(blank=True, help_text='NID or Passport', max_length=64)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('nationality', models.CharField(blank=True, max_length=90)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.guests.models.guest_photo_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guests', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='guests_gues_phone_n_6ab6e8_idx'), models.Index(fields=['full_name'], name='guests_gues_full_na_8e09c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('phone_number',), name='uniq_guest_phone')],
            },
        ),
    ]
