# Generated by Django 5.2.1 on 2025-10-26 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nid_passport', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('relation', models.CharField(blank=True, help_text='Relation to main guest (optional)', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='guests.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
