# Generated by Django 5.2.1 on 2025-10-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guestcompanion'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='company',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
