# Generated by Django 5.2.1 on 2025-10-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='due_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gross_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='net_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nightly_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Store in poisha (e.g., 100.00 BDT -> 10000)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Store in poisha (e.g., 100.00 BDT -> 10000)'),
        ),
    ]
