# Generated by Django 5.2.1 on 2025-11-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nightly_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Store in BDT (integer taka, e.g., 100)', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Store in BDT (integer taka, e.g., 100)'),
        ),
    ]
