# Generated by Django 5.2.1 on 2025-11-11 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_nightly_rate_alter_payment_amount'),
        ('guests', '0003_guest_company'),
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('CHECKED_IN', 'Checked-In'), ('CHECKED_OUT', 'Checked-Out'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='booking_room_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_check_out_after_in'),
        ),
    ]
