# Generated by Django 5.2.1 on 2025-12-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_extra_amount_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('RESERVED', 'Reserved'), ('CHECKED_IN', 'Checked-In'), ('CHECKED_OUT', 'Checked-Out'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
