# Generated by Django 5.2.1 on 2025-10-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('post', models.CharField(blank=True, max_length=40, null=True)),
                ('upozilla', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='site_header_image')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('established', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/logo_fav/', verbose_name='site_logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/logo_fav/', verbose_name='site_fav')),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=18, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('footer', models.CharField(blank=True, max_length=255)),
                ('footer_description', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
